version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///auth_app.db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:8000/api/v1/
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
